import type { Metadata } from "next";
import "./globals.css";
import Header from "@/ui/header";
import Footer from "@/ui/footer";

export const metadata: Metadata = {
    title: "Reliwe",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`antialiased`}
            >
				<Header />
				
                {children}

				<Footer />
            </body>
        </html>
    );
}
