import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
    title: "Reliwe",
    description: "Generated by create next app",
};

export default function GlobalLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body className="antialiased">{children}</body>
        </html>
    );
}