import type { Metadata } from "next";
import Footer from "@/ui/footer";
import "./globals2.css";

export const metadata: Metadata = {
    title: "Reliwe",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    
    return (
        <html lang="en">
            <body
                className={`antialiased`}
            >
                {children}
				<Footer />
            </body>
        </html>
    );
}
